export const MARKETPLACE_CATEGORIES = [
  'Graphics & Design', 'Logo Design', 'Brand Style Guides', 'Business Cards & Stationery', 'Packaging & Label Design', 'Book & Album Covers', 'Illustration', 'Character Design', 'Cartoon & Comics', 'Pattern Design', 'Presentation Design', 'Infographic Design', 'Vector Tracing', 'Portraits & Caricatures', 'Architecture & Interior Design', 'Landscape Design', 'Fashion Design', 'Jewelry Design', '3D Industrial Design', '3D Architecture',
  'Web Development', 'Frontend Development', 'Backend Development', 'Full Stack Development', 'Mobile App Development', 'Desktop App Development', 'WordPress', 'Shopify', 'Wix', 'Webflow', 'Ecommerce Development', 'Game Development', 'Chatbot Development', 'AI Applications', 'API Integration', 'Automation & Scripting', 'Cloud Computing', 'DevOps', 'Cybersecurity', 'QA & Testing', 'Bug Fixes', 'Database Design', 'Data Engineering', 'Computer Vision', 'Machine Learning', 'Blockchain & Crypto', 'AR/VR Development', 'IoT Development',
  'Digital Marketing', 'Search Engine Optimization', 'Local SEO', 'Search Engine Marketing', 'Social Media Marketing', 'Social Media Management', 'Influencer Marketing', 'Email Marketing', 'Marketing Strategy', 'Content Marketing', 'Video Marketing', 'Display Advertising', 'Book & Podcast Promotion', 'Community Management', 'Public Relations', 'Lead Generation', 'Marketing Analytics', 'Affiliate Marketing', 'Crowdfunding', 'App Marketing', 'Music Promotion',
  'Writing & Translation', 'Articles & Blog Posts', 'Website Content', 'Technical Writing', 'Copywriting', 'Email Copy', 'Social Media Copy', 'Product Descriptions', 'Book & Ebook Writing', 'Scriptwriting', 'Creative Writing', 'Resume Writing', 'LinkedIn Profiles', 'Proofreading & Editing', 'Research & Summaries', 'Legal Writing', 'Business Naming', 'Translation', 'Localization', 'Transcription', 'Language Lessons', 'Voiceover Scripts',
  'Video & Animation', 'Video Editing', 'Short Form Video', 'Long Form Video', 'Explainer Videos', '3D Product Animation', 'Character Animation', 'Logo Animation', 'Motion Graphics', 'Whiteboard Animation', 'Subtitles & Captions', 'Visual Effects', 'Music Videos', 'Wedding Videos', 'Drone Videography', 'Video Ads', 'Live Action Explainers', 'Stop Motion', 'Intro & Outro Videos', 'Video Advice',
  'Music & Audio', 'Voice Over', 'Mixing & Mastering', 'Producers & Composers', 'Singers & Vocalists', 'Session Musicians', 'Songwriters', 'Jingles & Intros', 'Podcast Production', 'Audiobook Production', 'Sound Design', 'DJ Drops', 'Beat Making', 'Music Transcription', 'Audio Editing', 'Meditation Music', 'Sonic Branding',
  'Business', 'Business Consulting', 'Market Research', 'Financial Consulting', 'Business Plans', 'Legal Consulting', 'HR Consulting', 'Project Management', 'Supply Chain Management', 'Virtual Assistant', 'Data Entry', 'Customer Care', 'Business Presentations', 'Ecommerce Management', 'Tax Consulting', 'Fundraising Consulting', 'Career Consulting', 'Event Planning', 'Sustainability Consulting', 'Operations Management',
  'Lifestyle', 'Online Tutoring', 'Fitness & Nutrition', 'Life Coaching', 'Relationship Advice', 'Travel Planning', 'Gaming', 'Astrology & Readings', 'Arts & Crafts', 'Wellness', 'Spirituality', 'Cooking Lessons', 'Pet Care', 'Family & Genealogy', 'Modeling & Acting', 'Dance Lessons', 'Photography', 'Food Photography', 'Product Photography', 'Real Estate Photography', 'Aerial Photography',
  'Data', 'Data Analysis', 'Data Visualization', 'Data Cleaning', 'Data Scraping', 'Dashboards', 'Statistical Analysis', 'Excel Services', 'Power BI', 'Tableau', 'SQL', 'Survey Analysis', 'Financial Modeling', 'GIS Mapping', 'Presentation Analytics', 'Conversion Rate Optimization', 'Custom Category'
];

export const CATEGORY_OPTIONS = ['All categories', ...MARKETPLACE_CATEGORIES];
