import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Brush, Camera, ChevronRight, ImagePlus, Sparkles, WandSparkles } from 'lucide-react';
import AIImageGenerator from '../components/AIImageGenerator';
import PhotoEditor from '../components/PhotoEditor';

const COLORS = { ink: '#18221f', moss: '#1f6f5c', leaf: '#e8f5ee', cream: '#fbfaf7', line: '#ebe9e3', muted: '#7a817d', gold: '#c58b32' };

export default function CreativeStudio() {
  const [activeTab, setActiveTab] = useState('photo-editor');
  const [imageGeneratorOpen, setImageGeneratorOpen] = useState(false);

  return <div className="mx-auto max-w-[1600px] pb-10"><div className="flex flex-wrap items-end justify-between gap-5 mb-6"><div><p className="text-[10px] uppercase tracking-[0.2em] font-bold" style={{ color: COLORS.moss }}>Build & grow / creative studio</p><h1 className="mt-2 text-3xl md:text-5xl font-bold tracking-[-0.06em]" style={{ color: COLORS.ink }}>Make the visual work feel intentional.</h1><p className="mt-3 max-w-3xl text-sm leading-6" style={{ color: COLORS.muted }}>Create new imagery with AI or refine your own photos in a professional browser editor. Your source files stay in the browser until you choose to export them.</p></div><div className="flex items-center gap-2"><Link to="/dashboard" className="h-10 px-3 rounded-xl border bg-white text-xs font-bold flex items-center gap-2" style={{ borderColor: COLORS.line, color: COLORS.ink }}><ChevronRight size={14} className="rotate-180" /> Dashboard</Link><Link to="/ai-store" className="h-10 px-3 rounded-xl border bg-white text-xs font-bold flex items-center gap-2" style={{ borderColor: COLORS.line, color: COLORS.ink }}>Portfolio studio <ArrowUpRight size={14} /></Link></div></div>
    <div className="rounded-3xl border bg-white p-2" style={{ borderColor: COLORS.line }}><div className="flex flex-wrap items-center justify-between gap-3 border-b px-2 pb-2" style={{ borderColor: COLORS.line }}><div className="flex items-center gap-1"><button onClick={() => setActiveTab('photo-editor')} className="flex items-center gap-2 rounded-2xl px-4 py-3 text-xs font-bold" style={{ backgroundColor: activeTab === 'photo-editor' ? COLORS.ink : 'transparent', color: activeTab === 'photo-editor' ? '#fff' : COLORS.muted }}><Brush size={15} /> Photo Editor</button><button onClick={() => setActiveTab('ai-image')} className="flex items-center gap-2 rounded-2xl px-4 py-3 text-xs font-bold" style={{ backgroundColor: activeTab === 'ai-image' ? COLORS.ink : 'transparent', color: activeTab === 'ai-image' ? '#fff' : COLORS.muted }}><Sparkles size={15} /> AI Image Studio</button></div><div className="flex items-center gap-2 px-3 text-[10px] font-bold" style={{ color: COLORS.muted }}><span className="h-2 w-2 rounded-full" style={{ backgroundColor: activeTab === 'photo-editor' ? COLORS.moss : COLORS.gold }} />{activeTab === 'photo-editor' ? 'Client-side editing' : 'NVIDIA AI generation'}</div></div>{activeTab === 'photo-editor' ? <div className="p-2 md:p-4"><PhotoEditor /></div> : <div className="min-h-[640px] p-5 md:p-10"><div className="mx-auto max-w-3xl rounded-3xl border bg-[#fafbf9] p-6 text-center" style={{ borderColor: COLORS.line }}><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl" style={{ backgroundColor: COLORS.leaf, color: COLORS.moss }}><Camera size={24} /></div><h2 className="mt-5 text-2xl font-bold tracking-[-0.05em]" style={{ color: COLORS.ink }}>AI Image Studio</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6" style={{ color: COLORS.muted }}>Generate a visual asset or edit a reference image with the saved server-side AI provider.</p><button onClick={() => setImageGeneratorOpen(true)} className="mt-6 inline-flex items-center gap-2 rounded-xl px-4 py-3 text-xs font-bold text-white" style={{ backgroundColor: COLORS.moss }}><WandSparkles size={15} /> Open AI Image Studio <ArrowUpRight size={14} /></button></div></div>}</div><p className="mt-4 flex items-center justify-center gap-2 text-[10px]" style={{ color: COLORS.muted }}><ImagePlus size={12} /> Photo Editor uses the supplied CE.SDK starter kit. Add your license in <code>client/.env.local</code>.</p>{imageGeneratorOpen && <AIImageGenerator isOpen={imageGeneratorOpen} onClose={() => setImageGeneratorOpen(false)} />}</div>;
}
